data "aws_ami" "MyAMI" {
  most_recent = true

  filter {
    name   = "name"
    # Filter by name generated by packer
    values = ["MyAMI*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["self"] # Canonical
}

